### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by sergiopvilar** [AnansiPodcast/website#3]
As a user I would like to visit the site and in the home page download the latest release of Anansi.

**Acceptance criteria:**
- A screenshot or some featured call showing app's UI
- A button do download the latest beta with the version number
- Info about the latest version and download link can be found [here](http://anansi-podcast.herokuapp.com/latest/beta/info)

![Layout](http://d.pr/i/13jC1.jpg)

[Download PSD Layout](http://d.pr/f/1bEjA)

**Comment by sergiovilar** [comment]
[PSD Layout](http://d.pr/f/1bDMW)

**Comment by sergiopvilar** [comment]
Closed in 0faa8fbf7d9a7fc8f051e31298042b171019be88, 4a8eda37c446320ba5d30b20785b98512ac61a41 and b7f762250d710eb0a35bb15cab3410fda1debe84
